services:
  kestrelsnest-host:
    image: kestrelsnest-host
    build: 
      context: .
      dockerfile: ./kestrelsnest-host/Dockerfile
    ports:
      - "127.0.0.4:80:80"
    volumes:
      - ./logs/kestrelsnest-host/:/var/log/nginx