services:
  kestrelsnest-host:
    image: kestrelsnest-host
    build: 
      context: .
      dockerfile: ./kestrelsnest-host/Dockerfile
        
  kestrelsdocker-reversproxy:
    image: kestrelsdocker-reversproxy
    build:
      context: .
      dockerfile: ./KestrelsDocker-ReversProxy/Dockerfile