services:
  
  # The Host for the Content of the KestralsNest Website
  kestrelsnest-host:
    image: ghcr.io/aceofkestrels/kestrelsnest-host:prod
    networks:
      kestrelsnest-host: {}
    volumes:
      - ./logs/kestrelsnest-host/nginx/:/var/log/nginx/
  
  # The ReversProxy that Routes the Web Traffic to the corresponding backend servers
  kestrelsdocker-reversproxy:
    image: ghcr.io/aceofkestrels/kestrelsdocker-reversproxy:prod
    networks:
      kestrelsnest-host: {}
      kestrelwiki-host: {}
    volumes:
      - ./logs/KestrelsDocker-ReversProxy/caddy:/var/log/caddy/
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - DNS_TOKEN={$CLOUDFLARE_TOKEN}
      - ADMIN_MAIL={$ADMIN_EMAIL}
      - WEB_ADDRESS={$WEB_ADRESS}
    dns:
      - 1.1.1.1
      - 8.8.8.8 

  # The API host of the KetrelsWiki
  kestrelwiki-host:
    image: ghcr.io/aceofkestrels/kestrelwiki-host:prod
    networks:
      kestrelwiki-host: {}
      keydb-host: {}
    environment:
      - WEBPAGE_REPOSITORY={$WEBPAGE_GIT_REPO}
    volumes:
      - /logs/kestrelwiki-host/api:/var/log/kestrelswiki
  
  # The redis to be used with the KestrelsWiki
  kestrelsdocker-keyDB:
    image: eqalpha/keydb
    networks:
      keydb-host: {}
  
networks:
  kestrelsdocker-reversproxy:
    internal: false
  kestrelsnest-host:
    internal: false
  kestrelwiki-host:
    internal: false
  keydb-host:
    internal: true