services:
  
  # The Host for the Content of the KestralsNest Website
  kestrelsnest-host:
    image: ghcr.io/aceofkestrels/kestrelsnest-host:prod
    networks:
      kestrelsnest-host: {}
    volumes:
      - ./logs/kestrelsnest-host/nginx/:/var/log/nginx/
    restart: always  
    
  # The ReversProxy that Routes the Web Traffic to the corresponding backend servers
  kestrelsdocker-reversproxy:
    image: ghcr.io/aceofkestrels/kestrelsdocker-reversproxy:prod
    networks:
      kestrelsnest-host: {}
      kestrelwiki-host: {}
    volumes:
      - ./logs/kestrelsdocker-reversproxy/caddy/:/var/log/caddy/
      - ./data/caddy:/data
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - DNS_TOKEN=${CLOUDFLARE_TOKEN}
      - ADMIN_MAIL=${ADMIN_EMAIL}
      - WEB_ADDRESS=${WEB_ADRESS}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: always

  # The API host of the KetrelsWiki
  kestrelwiki-host:
    image: ghcr.io/aceofkestrels/kestrelwiki-host:prod
    networks:
      kestrelwiki-host: {}
      valkey-host: {}
    environment:
      - CONTENT_REPOSITORY=${CONTENT_GIT_REPOSITORY}
    volumes:
      - /logs/kestrelwiki-host/api:/var/log/kestrelswiki
    restart: always
  
  # The redis to be used with the KestrelsWiki
  kestrelsdocker-valkey:
    image: valkey/valkey:8.0.2-alpine3.21
    networks:
      valkey-host: {}
    restart: always
  
networks:
  kestrelsdocker-reversproxy:
    internal: false
  kestrelsnest-host:
    internal: false
  kestrelwiki-host:
    internal: false
  valkey-host:
    internal: true
