name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Step 2: Set up Docker Compose and install yq
      - name: Install Docker Compose and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose yq
        
      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          install: true
      
      # Step 5:  Build and push Docker images
      - name: Build and push Docker images
        run: |
          services=$(docker-compose -f build-compose.yml config --services)
          for service in $services; do
            echo "Processing service: $service"
            image_name=$(docker-compose -f build-compose.yml config | awk -v srv="$service" '
              $0 ~ srv {found=1}
              found && /image:/ {print $2; exit}
            ')
            if [ -z "$image_name" ]; then
              echo "Image name not found for service: $service"
              exit 1
            fi
            # Convert image_name_with_registry to lowercase
            image_name_with_registry="ghcr.io/${{ github.repository_owner }}/${image_name}"
            image_name_with_registry=$(echo "$image_name_with_registry" | tr '[:upper:]' '[:lower:]')
            echo "Building and pushing: $image_name_with_registry"
          
            # Define the build context and Dockerfile path
            build_context="."
            dockerfile_path="./${image_name}/Dockerfile"
          
            # Check if a specific build context or Dockerfile is defined for the service
            service_build_context=$(docker-compose -f build-compose.yml config | awk -v srv="$service" '
              $0 ~ srv {found=1}
              found && /context:/ {print $2; exit}
            ')
            service_dockerfile=$(docker-compose -f build-compose.yml config | awk -v srv="$service" '
              $0 ~ srv {found=1}
              found && /dockerfile:/ {print $2; exit}
            ')
          
            # Override defaults if specific paths are defined
            if [ -n "$service_build_context" ]; then
              build_context="$service_build_context"
            fi
            if [ -n "$service_dockerfile" ]; then
              dockerfile_path="$service_dockerfile"
            fi
          
            # Build and push the Docker image
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --file "$dockerfile_path" \
              --tag "$image_name_with_registry" \
              --push \
              "$build_context"
          done
      
      
      # Step 6: Verify pushed images
      - name: Verify pushed images
        run: |
          services=$(docker-compose -f build-compose.yml config --services)
          for service in $services; do
            # Use yq to extract the image name, handling special characters in service names
            image_name=$(docker-compose -f build-compose.yml config | awk -v srv="$service" '
              $0 ~ srv {found=1}
              found && /image:/ {print $2; exit}
            ')
            if [ -z "$image_name" ]; then
              echo "Image name not found for service: $service"
              exit 1
            fi
            image_name_with_registry="ghcr.io/${{ github.repository_owner }}/${image_name}"
            image_name_with_registry=$(echo "$image_name_with_registry" | tr '[:upper:]' '[:lower:]')
            if docker pull "$image_name_with_registry"; then
              echo "Successfully pushed and verified: $service ($image_name_with_registry)"
            else
              echo "Failed to verify image: $service"
              exit 1
            fi
          done
      